-- Run once in a Snowflake worksheet before starting the API.
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS PHARMACY;
CREATE SCHEMA IF NOT EXISTS PHARMACY.PUBLIC;

-- The API creates users / medicines / orders / order_items itself on startup
-- (SQLAlchemy create_all) and seeds the 18-medicine catalogue.
-- Grant the app role access:
-- GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE <APP_ROLE>;
-- GRANT USAGE ON DATABASE PHARMACY TO ROLE <APP_ROLE>;
-- GRANT USAGE, CREATE TABLE ON SCHEMA PHARMACY.PUBLIC TO ROLE <APP_ROLE>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PHARMACY.PUBLIC TO ROLE <APP_ROLE>;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PHARMACY.PUBLIC TO ROLE <APP_ROLE>;
