"""removed previously added columns

Revision ID: edb5472fef31
Revises: 176d860746fb
Create Date: 2026-08-21 15:43:26.611400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edb5472fef31'
down_revision: Union[str, Sequence[str], None] = '176d860746fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'updated_at')
    op.drop_column('support_tickets', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('support_tickets', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
